In [3]:
# Python Array Module
import array as myarray

In [7]:
# Creating an array
arr=myarray.array('i',[1,2,3])
arr1=myarray.array('d',[1.0,2.1,2.4,2.5,2.6])
arr2=myarray.array('u',['a','b','c','d'])

# To Check TypeCodes
print(arr.typecode)
print(arr1.typecode)
print(arr2.typecode)

# First Look at the Array
print(arr)
print(arr1)
print(arr2)

# To print length of the Array
print(len(arr))
print(len(arr1))
print(len(arr2))

i
d
u
array('i', [1, 2, 3])
array('d', [1.0, 2.1, 2.4, 2.5, 2.6])
array('u', 'abcd')
3
5
4


In [10]:
for i in range(0,len(arr)):
    print(arr[i],end=" ")
print("\n")

for i in range(0,len(arr1)):
    print(arr1[i],end=" ")
print("\n")

for i in range(0,len(arr2)):
    print(arr2[i],end=" ")
print("\n")

1 2 3 

1.0 2.1 2.4 2.5 2.6 

a b c d 



In [15]:
# Assessing Elements from an array using index values

x=list(range(1,100,2))

# Printing the Array
new_array=myarray.array('i',x)
print("Elements in the Array are: ")
for i in range(0,len(new_array)):
    print(new_array[i],end=" ")
print("\n")

# Accessing the array at index 25
print("Element at index 25: ",new_array[25])

Elements in the Array are: 
1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99 

Element at index 25:  51


In [18]:
# Adding Elements to an Array

new_arr=myarray.array('i',[1,2,4,5,6,8])
for i in range(0,len(new_arr)):
    print(new_arr[i],end=" ")
print("\n")

# Using insert
new_arr.insert(1,10)
new_arr.insert(2,11)
for i in range(0,len(new_arr)):
    print(new_arr[i],end=" ")
print("\n")

# Using append
new_arr.append(12)
new_arr.append(111)
for i in range(0,len(new_arr)):
    print(new_arr[i],end=" ")
print("\n")

1 2 4 5 6 8 

1 10 11 2 4 5 6 8 

1 10 11 2 4 5 6 8 12 111 



In [24]:
# Updating Elements in Array

new_arr1=myarray.array('i',[1,2,4,5,6,8])
for i in range(0,len(new_arr1)):
    print(new_arr1[i],end=" ")
print("\n")

# Updating the Array
new_arr1[2]=22             # Assigned new value at index 2
for i in range(0,len(new_arr1)):
    print(new_arr1[i],end=" ")
print("\n")

1 2 4 5 6 8 

1 2 22 5 6 8 



In [29]:
# Deleting Elements in Array

new_arr2=myarray.array('i',[1,2,3,4,5,6,8])

# Using pop
new_arr2.pop(2)          # Removes the Element at Index 2
for i in range(0,len(new_arr2)):
    print(new_arr2[i],end=" ")
print("\n")

# Using remove
new_arr2.remove(2)       # Removes the Element 2
for i in range(0,len(new_arr2)):
    print(new_arr2[i],end=" ")
print("\n")

1 2 4 5 6 8 

1 4 5 6 8 



In [34]:
# Slicing 

y=list(range(1,101,2))
arr=myarray.array('i',y)
print(arr)

arr0=arr[0:10]
for i in range(0,len(arr0)):
    print(arr0[i],end=" ")
print("\n")

# Negative Indexing 
arr0=arr[10:-10]
for i in range(0,len(arr0)):
    print(arr0[i],end=" ")
print("\n")


arr0=arr[::2]
for i in range(0,len(arr0)):
    print(arr0[i],end=" ")
print("\n")

# Reversing the order using Slicing 
arr0=arr[::-1]
for i in range(0,len(arr0)):
    print(arr0[i],end=" ")
print("\n")

array('i', [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])
1 3 5 7 9 11 13 15 17 19 

21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 

1 5 9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93 97 

99 97 95 93 91 89 87 85 83 81 79 77 75 73 71 69 67 65 63 61 59 57 55 53 51 49 47 45 43 41 39 37 35 33 31 29 27 25 23 21 19 17 15 13 11 9 7 5 3 1 



In [42]:
# Searching

# using index() method

x=list(range(1,61,5))
arr=myarray.array('i',x)
for i in range(0,len(arr)):
    print(arr[i],end=" ")
print("\n")

index=arr.index(56)
result=arr[index]
print(index,result)

1 6 11 16 21 26 31 36 41 46 51 56 

11 56


In [48]:
# Sorting Operations
sort_array=myarray.array('i',[1,2,4,5,6,8,10])
sorted_array=sort_array.tolist()
print(sorted_array)

# Ascending Order
sorted_array.sort()
print("Ascending: ",sorted_array)

# Descending Order
sorted_array.sort(reverse=True)
print("Descending: ",sorted_array)

[1, 2, 4, 5, 6, 8, 10]
Ascending:  [1, 2, 4, 5, 6, 8, 10]
Descending:  [10, 8, 6, 5, 4, 2, 1]


In [49]:
## Numpy Arrays

In [60]:
# Creating Numpy Arrays
import numpy as np

array=np.array([1,2,4,5,6,7,8])
print(array)
print("\n")

# Creating an Array with all Zeros
zeros=np.zeros((2,2))
print(zeros)
print("\n")

# Creating an Array with all Ones
Ones=np.ones((2,2))
print(Ones)
print("\n")

# Creating an Array with constant Values
const=np.full((2,2),5)
print(const)
print("\n")

# Creating an identity matrix
iden=np.eye(2)
print(iden)
print("\n")

# Creating an Array with random Values
random=np.random.random((2,2))
print(random)

[1 2 4 5 6 7 8]


[[0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]]


[[5 5]
 [5 5]]


[[1. 0.]
 [0. 1.]]


[[0.94736455 0.54006642]
 [0.27164296 0.02345656]]


In [73]:
# 1D, 2D and 3D Arrays

# 0 Dimensional Array
zerod=np.array(1)
print(zerod)
print("\n")

# 1 Dimensional Array
oned=np.array([1,2])
print(oned)
print("\n")

# 2 Dimensional Array
twod=np.array([[1,2],[4,6]])
print(twod)
print("\n")

# 2 Dimensional Array
threed=np.array([[1,2,5],[4,6,2],[2,4,6],[1,2,5]])
print(threed)
print("\n")

# Multi Dimensional Array
multid=np.array([1,2,4,5,6,8],ndmin=4)
print(multid)
print("\n")

# To check the dimensions of the array

print(zerod.ndim)
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)
print(multid.ndim)

1


[1 2]


[[1 2]
 [4 6]]


[[1 2 5]
 [4 6 2]
 [2 4 6]
 [1 2 5]]


[[[[1 2 4 5 6 8]]]]


0
1
2
2
4


In [79]:
# CRUD Operations on numpy arrays

# Reading From a Numpy Array
array=np.array([1,2,4,5,6,8])
for i in range(0,len(array)):
    print(array[i],end=" ")
print("\n")

# Updating an Element in a Numpy Array, we make use of indexing here.
array[0]=2
print(array)
print("\n")

# Deleting an Element from a Numpy Array
array=np.delete(array,2)
print(array)
print("\n")

1 2 4 5 6 8 

[2 2 4 5 6 8]


[2 2 5 6 8]




In [82]:
# Searching Elements in numpy array
x=list(range(0,2000,5))
search_array=np.array(x)

# Searching the Element 550
res=np.where(search_array==550)
print(res)

# Checking if the returning index is true
print(search_array[110])

(array([110], dtype=int64),)
550


In [87]:
# Sorting Elements in a numpy array
sample_sort_array=np.array([1,2,4,6,5,8,7])

# Sorting the numpy array using sort()
x=np.sort(sample_sort_array)
x

array([1, 2, 4, 5, 6, 7, 8])

In [89]:
# Mathematical Operation on numpy arrays
a=np.array([[1,2,4]],dtype=np.int64)
b=np.array([[4,5,6]],dtype=np.int64)

# Adding 2 Numpy Arrays
addition = np.add(a,b)
print(addition)
print("\n")

# Subtracting 2 Numpy Arrays
subtraction = np.subtract(a,b)
print(subtraction)
print("\n")

# Subtracting 2 Numpy Arrays
subtraction = np.subtract(a,b)
print(subtraction)
print("\n")

# Multiplying 2 Numpy Arrays
multiply = np.multiply(a,b)
print(multiply)
print("\n")

# Dividing 2 Numpy Arrays
divide = np.divide(a,b)
print(divide)
print("\n")

# Square root of Numpy Arrays
sqrt = np.sqrt(a)
sqrt1 = np.sqrt(b)
print(sqrt)
print(sqrt1)
print("\n")

# Transpose of Numpy Arrays
x=np.array([[1,2,4],[2,4,5],[5,6,7]])
transpose=np.transpose(x)
print(x)
print("\n")
print(sqrt1)

[[ 5  7 10]]


[[-3 -3 -2]]


[[-3 -3 -2]]


[[ 4 10 24]]


[[0.25       0.4        0.66666667]]


[[1.         1.41421356 2.        ]]
[[2.         2.23606798 2.44948974]]
